# Generated by Django 4.2.5 on 2023-09-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("patronymic", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_stock", "в наличии"), ("on_delivery", "выданы")],
                        default="in_stock",
                        max_length=11,
                    ),
                ),
                ("date_deliver", models.DateTimeField(blank=True, null=True)),
                ("date_hand_in", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("patronymic", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name="reader",
            constraint=models.UniqueConstraint(fields=("first_name", "last_name", "patronymic"), name="unique_reader"),
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="books.author"),
        ),
        migrations.AddField(
            model_name="book",
            name="reader",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="books.reader"
            ),
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(fields=("first_name", "last_name", "patronymic"), name="unique_author"),
        ),
    ]
